### ISSUE TITLE
This script is gone

### ISSUE THREAD

**Issue by willtome** [ansible/product-demos#78]
https://github.com/ansible/product-demos/blob/81f35e8d67bd6971ae0f75ad0f7ec222cd757daa/collections/ansible_collections/demo/cloud/roles/aws/templates/aws_windows_userdata.j2#L20

**Comment by MKletz** [comment]
This was moved [here](https://github.com/ansible/ansible-documentation/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1) but we're really not supposed to be using this anymore. Not sure what the best patch forward is.

**Comment by willtome** [comment]
Is this still a problem since the cloud demos now use https://github.com/ansible-content-lab/aws.infrastructure_config_demos? Maybe the aws stuff should just come out completely

**Comment by jce-redhat** [comment]
closing this since the the version of the script used in [aws.infrastructure_config_demos](https://github.com/ansible-content-lab/aws.infrastructure_config_demos) is essentially the same as the one in the [ansible-documentation repo](https://github.com/ansible/ansible-documentation/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1) other than some cosmetic changes.
